from __future__ import annotations

import hashlib
import json
import sqlite3
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import parse_qs, unquote_plus, urlparse

from html_exports import write_html_outputs
from report_center import generate_html_report

CHROME_EPOCH = datetime(1601, 1, 1, tzinfo=timezone.utc)

TRANSITIONS = {
    0: "Enlace (link)",
    1: "URL escrita (typed)",
    2: "Marcador / acceso automático (auto_bookmark)",
    3: "Subframe automático (auto_subframe)",
    4: "Subframe manual (manual_subframe)",
    5: "Navegación generada (generated)",
    6: "Apertura automática (auto_toplevel)",
    7: "Envío de formulario (form_submit)",
    8: "Recarga (reload)",
    9: "Palabra clave (keyword)",
    10: "Búsqueda generada (keyword_generated)",
}

VISIT_SOURCES = {
    0: "Sincronización (sync)",
    1: "Navegación local (browsed)",
    2: "Extensión (extension)",
    3: "Importado desde Firefox",
    4: "Importado desde Internet Explorer",
    5: "Importado desde Safari",
    6: "Actor / fuente interna",
    7: "Importado por migración del sistema",
}

DOWNLOAD_STATES = {
    0: "En progreso",
    1: "Completa",
    2: "Cancelada",
    3: "Estado heredado",
    4: "Interrumpida",
}


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()



def is_internal_analyzer_url(value):
    """Detect only local files generated by this analyzer itself."""
    if not value:
        return False
    try:
        parsed = urlparse(str(value))
        if parsed.scheme.lower() != "file":
            return False
        path = (parsed.path or "").replace("\\", "/").lower()
        return (
            "analizador-historial-navegacion-windows" in path
            and "/resultados/" in path
        )
    except Exception:
        return False


def _clean_display_rows(urls, timeline, searches):
    urls = [r for r in urls if not is_internal_analyzer_url(r.get("url", ""))]
    timeline = [r for r in timeline if not is_internal_analyzer_url(r.get("url", ""))]
    searches = [r for r in searches if not is_internal_analyzer_url(r.get("url", ""))]
    return urls, timeline, searches

def chrome_time(value):
    if value in (None, "", 0, "0"):
        return ""
    try:
        dt = CHROME_EPOCH + timedelta(microseconds=int(value))
        return dt.isoformat().replace("+00:00", "Z")
    except Exception:
        return ""


def duration_seconds(value):
    if value in (None, "", 0, "0"):
        return ""
    try:
        return round(int(value) / 1_000_000, 3)
    except Exception:
        return ""


def transition_name(value):
    try:
        raw = int(value)
        return TRANSITIONS.get(raw & 0xFF, f"desconocido_{raw & 0xFF}")
    except Exception:
        return ""


def connect_readonly(path: Path):
    return sqlite3.connect(f"{path.resolve().as_uri()}?mode=ro", uri=True)


def get_tables(conn):
    return {
        row[0]
        for row in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        ).fetchall()
    }


def get_columns(conn, table):
    return {
        row[1]
        for row in conn.execute(f'PRAGMA table_info("{table}")').fetchall()
    }



def extract_urls(conn):
    if "urls" not in get_tables(conn):
        return []
    cols = get_columns(conn, "urls")
    wanted = [
        "id", "url", "title", "visit_count",
        "typed_count", "last_visit_time", "hidden"
    ]
    available = [c for c in wanted if c in cols]
    if not available:
        return []

    cur = conn.execute(
        "SELECT " + ", ".join(f'"{c}"' for c in available) + " FROM urls"
    )
    rows = []
    for dbrow in cur.fetchall():
        item = dict(zip(available, dbrow))
        item["ultima_visita_utc"] = chrome_time(item.get("last_visit_time"))
        try:
            item["dominio"] = urlparse(item.get("url", "")).netloc.lower()
        except Exception:
            item["dominio"] = ""
        rows.append(item)
    return rows


def visit_source_map(conn):
    if "visit_source" not in get_tables(conn):
        return {}
    cols = get_columns(conn, "visit_source")
    if not {"id", "source"}.issubset(cols):
        return {}
    return {
        int(visit_id): int(source)
        for visit_id, source in conn.execute("SELECT id, source FROM visit_source")
    }


def extract_timeline(conn):
    tables = get_tables(conn)
    if not {"urls", "visits"}.issubset(tables):
        return []

    vc = get_columns(conn, "visits")
    uc = get_columns(conn, "urls")
    if "url" not in vc or "id" not in uc or "url" not in uc:
        return []

    select = [
        "visits.id AS visit_id",
        "visits.url AS url_id",
        "urls.url AS url",
    ]
    if "title" in uc:
        select.append("urls.title AS title")

    optional = [
        "visit_time", "from_visit", "transition", "segment_id",
        "visit_duration", "external_referrer_url", "opener_visit",
        "originator_cache_guid", "is_known_to_sync", "app_id"
    ]
    for col in optional:
        if col in vc:
            select.append(f'visits."{col}" AS "{col}"')

    query = f"""
        SELECT {", ".join(select)}
        FROM visits
        JOIN urls ON visits.url = urls.id
    """
    if "visit_time" in vc:
        query += " ORDER BY visits.visit_time"

    cur = conn.execute(query)
    names = [d[0] for d in cur.description]
    rows = [dict(zip(names, dbrow)) for dbrow in cur.fetchall()]

    visit_url = {int(r["visit_id"]): r.get("url", "") for r in rows if r.get("visit_id") is not None}
    source_map = visit_source_map(conn)

    for item in rows:
        item["fecha_utc"] = chrome_time(item.get("visit_time"))
        item["duracion_segundos"] = duration_seconds(item.get("visit_duration"))
        item["tipo_navegacion"] = transition_name(item.get("transition"))
        try:
            item["dominio"] = urlparse(item.get("url", "")).netloc.lower()
        except Exception:
            item["dominio"] = ""

        ref_id = item.get("from_visit")
        try:
            item["url_origen_visita"] = visit_url.get(int(ref_id), "") if ref_id else ""
        except Exception:
            item["url_origen_visita"] = ""

        visit_id = item.get("visit_id")
        try:
            source = source_map.get(int(visit_id), 1)
            item["origen_visita"] = VISIT_SOURCES.get(source, f"desconocido_{source}")
        except Exception:
            item["origen_visita"] = ""

    return rows


def parse_search(url):
    if not url:
        return None
    try:
        p = urlparse(url)
        host = p.netloc.lower()
        q = parse_qs(p.query)
        if "google." in host and "q" in q:
            return q["q"][0]
        if "bing.com" in host and "q" in q:
            return q["q"][0]
        if "duckduckgo.com" in host and "q" in q:
            return q["q"][0]
        if "search.yahoo." in host and "p" in q:
            return q["p"][0]
    except Exception:
        pass
    return None


def extract_searches(conn, timeline):
    out, seen = [], set()
    tables = get_tables(conn)
    dates = {r.get("url", ""): r.get("fecha_utc", "") for r in timeline}

    if {"keyword_search_terms", "urls"}.issubset(tables):
        kc = get_columns(conn, "keyword_search_terms")
        uc = get_columns(conn, "urls")
        if {"url_id", "term"}.issubset(kc) and {"id", "url"}.issubset(uc):
            query = """
                SELECT k.term, u.url
                FROM keyword_search_terms k
                JOIN urls u ON k.url_id = u.id
            """
            for term, url in conn.execute(query):
                term = term or ""
                url = url or ""
                key = (term, url)
                if key not in seen:
                    seen.add(key)
                    out.append({
                        "fecha_utc": dates.get(url, ""),
                        "dominio": urlparse(url).netloc.lower() if url else "",
                        "termino": term,
                        "url": url,
                        "fuente": "keyword_search_terms"
                    })

    for row in timeline:
        url = row.get("url", "")
        term = parse_search(url)
        if term:
            term = unquote_plus(term)
            key = (term, url)
            if key not in seen:
                seen.add(key)
                out.append({
                    "fecha_utc": row.get("fecha_utc", ""),
                    "dominio": urlparse(url).netloc.lower() if url else "",
                    "termino": term,
                    "url": url,
                    "fuente": "parametro_url"
                })
    return out


def extract_downloads(conn):
    if "downloads" not in get_tables(conn):
        return []

    dc = get_columns(conn, "downloads")
    wanted = [
        "id", "guid", "current_path", "target_path", "start_time", "end_time",
        "received_bytes", "total_bytes", "state", "danger_type",
        "interrupt_reason", "opened", "referrer", "site_url", "tab_url",
        "tab_referrer_url", "http_method", "by_ext_id", "by_ext_name",
        "mime_type", "original_mime_type", "etag", "last_modified"
    ]
    available = [c for c in wanted if c in dc]
    if not available:
        return []

    cur = conn.execute(
        "SELECT " + ", ".join(f'"{c}"' for c in available) + " FROM downloads"
    )
    names = [d[0] for d in cur.description]

    chains = {}
    if "downloads_url_chains" in get_tables(conn):
        cc = get_columns(conn, "downloads_url_chains")
        if {"id", "chain_index", "url"}.issubset(cc):
            for did, idx, url in conn.execute(
                "SELECT id, chain_index, url "
                "FROM downloads_url_chains ORDER BY id, chain_index"
            ):
                chains.setdefault(did, []).append((idx, url))

    out = []
    for row in cur.fetchall():
        item = dict(zip(names, row))
        item["inicio_utc"] = chrome_time(item.get("start_time"))
        item["fin_utc"] = chrome_time(item.get("end_time"))
        try:
            item["estado_descarga"] = DOWNLOAD_STATES.get(
                int(item.get("state")), f"desconocido_{item.get('state')}"
            )
        except Exception:
            item["estado_descarga"] = ""

        chain = chains.get(item.get("id"), [])
        item["url_inicial"] = chain[0][1] if chain else ""
        item["url_final"] = chain[-1][1] if chain else ""
        item["cadena_urls"] = " -> ".join(url for _, url in chain)

        item["dominio"] = ""
        for candidate in (
            item.get("site_url", ""),
            item.get("tab_url", ""),
            item.get("url_final", ""),
            item.get("url_inicial", ""),
            item.get("referrer", ""),
        ):
            try:
                host = urlparse(candidate or "").netloc.lower()
            except Exception:
                host = ""
            if host:
                item["dominio"] = host
                break

        out.append(item)
    return out




def regenerate_outputs(data, output_dir):
    """Regenera todos los informes HTML secundarios del análisis."""
    write_html_outputs(data, output_dir)


def analyze(history_path, output_dir):
    history_path = Path(history_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    digest = sha256_file(history_path)
    conn = connect_readonly(history_path)
    try:
        tables = sorted(get_tables(conn))
        urls = extract_urls(conn)
        timeline = extract_timeline(conn)
        urls, timeline, _ = _clean_display_rows(urls, timeline, [])
        searches = extract_searches(conn, timeline)
        urls, timeline, searches = _clean_display_rows(urls, timeline, searches)
        downloads = extract_downloads(conn)
    finally:
        conn.close()

    domain_counter = Counter(
        r.get("dominio", "") for r in timeline if r.get("dominio")
    )
    domains = [
        {"dominio": domain, "eventos": count}
        for domain, count in domain_counter.most_common()
    ]

    transition_counter = Counter(
        r.get("tipo_navegacion", "")
        for r in timeline if r.get("tipo_navegacion")
    )
    transitions = [
        {"tipo": name, "eventos": count}
        for name, count in transition_counter.most_common()
    ]

    source_counter = Counter(
        r.get("origen_visita", "")
        for r in timeline if r.get("origen_visita")
    )
    sources = [
        {"origen": name, "eventos": count}
        for name, count in source_counter.most_common()
    ]

    typed_urls = sorted(
        [r for r in urls if int(r.get("typed_count") or 0) > 0],
        key=lambda x: int(x.get("typed_count") or 0),
        reverse=True
    )

    top_pages = sorted(
        urls,
        key=lambda x: int(x.get("visit_count") or 0),
        reverse=True
    )[:50]

    daily_counter = Counter(
        (r.get("fecha_utc") or "")[:10]
        for r in timeline if r.get("fecha_utc")
    )
    actividad_diaria = [
        {"fecha": fecha, "eventos": eventos}
        for fecha, eventos in sorted(daily_counter.items())
    ]

    key_tables = [
        "urls", "visits", "visit_source", "keyword_search_terms",
        "downloads", "downloads_url_chains"
    ]
    cobertura = [
        {"estructura": name, "disponible": "Sí" if name in tables else "No"}
        for name in key_tables
    ]

    dates = [r.get("fecha_utc") for r in timeline if r.get("fecha_utc")]

    acquisition_log = history_path.parent / "adquisicion.txt"
    acquisition_text = ""
    if acquisition_log.exists():
        try:
            acquisition_text = acquisition_log.read_text(encoding="utf-8")
        except Exception:
            pass

    data = {
        "metadata": {
            "archivo": str(history_path.resolve()),
            "carpeta_evidencia": str(history_path.parent.resolve()),
            "sha256": digest,
            "tamano_bytes": history_path.stat().st_size,
            "fecha_analisis_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "fecha_analisis_local": datetime.now().astimezone().isoformat(timespec="seconds"),
            "primer_evento_utc": min(dates) if dates else "",
            "ultimo_evento_utc": max(dates) if dates else "",
            "tablas_detectadas": tables,
            "registro_adquisicion": acquisition_text,
        },
        "resumen": {
            "urls": len(urls),
            "visitas": len(timeline),
            "dominios": len(domains),
            "busquedas": len(searches),
            "descargas": len(downloads),
            "urls_escritas": len(typed_urls),
        },
        "urls": urls,
        "timeline": timeline,
        "dominios": domains,
        "busquedas": searches,
        "descargas": downloads,
        "tipos_navegacion": transitions,
        "origen_visitas": sources,
        "urls_escritas": typed_urls,
        "paginas_principales": top_pages,
        "actividad_diaria": actividad_diaria,
        "cobertura": cobertura,
    }

    (output_dir / "analisis.json").write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8"
    )

    write_html_outputs(data, output_dir)
    return data
